import React, { useState } from "react";
import {
  FileText,
  AlertTriangle,
  Send,
  CheckCircle,
  XCircle,
  Edit3,
  Save,
  ShieldCheck,
  Link2,
} from "lucide-react";
import type { ProposedAction } from "../../types/canonical";
import { formatBackendDate } from "../../lib/formatters";
import { useEvidence } from "../../context/EvidenceContext";
import { useAuth } from "../../context/AuthContext";
import { CAPABILITY_KEYS } from "../../config/capabilityKeys";

interface ActionDraftCardProps {
  action: ProposedAction;
  onDecision: (
    decision: "save_edit" | "submit_review" | "approve" | "reject" | "cancel" | "execute",
    notes?: string,
    editedFields?: Record<string, unknown>,
    rejectionReason?: string
  ) => Promise<void>;
  isUpdating?: boolean;
}

export const ActionDraftCard: React.FC<ActionDraftCardProps> = ({
  action,
  onDecision,
  isUpdating = false,
}) => {
  const { openEvidence } = useEvidence();
  const { hasCapability } = useAuth();

  const [isEditing, setIsEditing] = useState(false);
  const [subject, setSubject] = useState(action.draft_payload.subject || "");
  const [recipients, setRecipients] = useState(action.draft_payload.recipients?.join(", ") || "");
  const [body, setBody] = useState(action.draft_payload.body || "");
  const [notes, setNotes] = useState("");
  const [rejectionReason, setRejectionReason] = useState("");
  const [showRejectInput, setShowRejectInput] = useState(false);

  const canApprove = hasCapability(CAPABILITY_KEYS.ACTION_APPROVE);

  // Status-driven availability
  const isDraftOrPending = action.status === "draft" || action.status === "pending_review";
  const isApproved = action.status === "approved";

  const handleSaveEdit = async () => {
    await onDecision("save_edit", "Draft payload updated by operator", {
      subject,
      recipients: recipients.split(",").map((s) => s.trim()).filter(Boolean),
      body,
    });
    setIsEditing(false);
  };

  const handleApprove = async () => {
    await onDecision("approve", notes || undefined);
  };

  const handleReject = async () => {
    if (!rejectionReason.trim()) return;
    await onDecision("reject", undefined, undefined, rejectionReason);
    setShowRejectInput(false);
  };

  const handleExecute = async () => {
    await onDecision("execute", notes || undefined);
  };

  return (
    <div className="p-5 bg-neutral-950/70 border border-neutral-800 rounded-xl space-y-4 text-xs">
      {/* Mandatory Static Governance Banners (Rule 9) */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-2">
        <div className="p-2 rounded bg-neutral-900 border border-neutral-800 text-neutral-300 font-medium text-center">
          AI-generated draft
        </div>
        <div className="p-2 rounded bg-amber-500/10 border border-amber-500/20 text-amber-300 font-medium text-center">
          Not sent
        </div>
        <div className="p-2 rounded bg-sky-500/10 border border-sky-500/20 text-sky-300 font-medium text-center">
          Requires human approval
        </div>
        <div className="p-2 rounded bg-neutral-900 border border-neutral-800 text-neutral-400 text-center">
          No final decision has been made
        </div>
      </div>

      {/* Header Info */}
      <div className="flex flex-wrap items-start justify-between gap-3 pt-2">
        <div>
          <div className="flex items-center gap-2">
            <span className="font-semibold text-sm text-neutral-100 uppercase tracking-wide">
              {action.action_type.replace(/_/g, " ")}
            </span>
            <span className="px-2 py-0.5 rounded border border-neutral-700 bg-neutral-900 text-neutral-300 font-mono text-[10px]">
              {action.status}
            </span>
            <span className="px-2 py-0.5 rounded border border-amber-500/30 bg-amber-500/10 text-amber-300 font-mono text-[10px]">
              Risk: {action.risk_level}
            </span>
          </div>
          <div className="mt-1 text-[11px] text-neutral-400 font-mono">
            Action ID: {action.action_id} · Case: {action.case_id}
          </div>
        </div>

        <div className="text-right text-[11px] text-neutral-500 font-mono">
          <div>Generated by: {action.generated_by}</div>
          <div>Created: {formatBackendDate(action.created_at)}</div>
        </div>
      </div>

      {/* Labels */}
      {action.labels && action.labels.length > 0 && (
        <div className="flex flex-wrap items-center gap-1.5">
          <span className="text-[10px] text-neutral-500">Labels:</span>
          {action.labels.map((lbl, idx) => (
            <span
              key={idx}
              className="px-2 py-0.5 rounded bg-neutral-900 border border-neutral-800 text-neutral-300 font-mono text-[10px]"
            >
              {lbl}
            </span>
          ))}
        </div>
      )}

      {/* Action Payload Form / Display */}
      <div className="p-4 bg-neutral-900/60 border border-neutral-800 rounded-lg space-y-3">
        {action.draft_payload.subject !== undefined && (
          <div>
            <label className="text-[11px] font-medium text-neutral-400">Subject</label>
            {isEditing ? (
              <input
                type="text"
                value={subject}
                onChange={(e) => setSubject(e.target.value)}
                className="mt-1 w-full bg-neutral-950 border border-neutral-700 rounded px-3 py-1.5 text-neutral-100 text-xs"
              />
            ) : (
              <div className="mt-1 text-neutral-200 font-medium">
                {action.draft_payload.subject}
              </div>
            )}
          </div>
        )}

        {action.draft_payload.recipients && (
          <div>
            <label className="text-[11px] font-medium text-neutral-400">Recipients</label>
            {isEditing ? (
              <input
                type="text"
                value={recipients}
                onChange={(e) => setRecipients(e.target.value)}
                className="mt-1 w-full bg-neutral-950 border border-neutral-700 rounded px-3 py-1.5 text-neutral-100 font-mono text-xs"
              />
            ) : (
              <div className="mt-1 text-neutral-300 font-mono text-[11px]">
                {action.draft_payload.recipients.join(", ")}
              </div>
            )}
          </div>
        )}

        <div>
          <label className="text-[11px] font-medium text-neutral-400">Draft Body</label>
          {isEditing ? (
            <textarea
              rows={6}
              value={body}
              onChange={(e) => setBody(e.target.value)}
              className="mt-1 w-full bg-neutral-950 border border-neutral-700 rounded p-3 text-neutral-100 font-mono text-xs"
            />
          ) : (
            <div className="mt-1 p-3 bg-neutral-950/80 rounded border border-neutral-800 text-neutral-200 whitespace-pre-wrap font-mono text-[11px]">
              {action.draft_payload.body}
            </div>
          )}
        </div>
      </div>

      {/* Policy Checks */}
      {action.policy_checks && action.policy_checks.length > 0 && (
        <div className="space-y-2">
          <div className="text-[11px] font-semibold text-neutral-400 uppercase tracking-wider flex items-center gap-1.5">
            <ShieldCheck className="w-3.5 h-3.5 text-emerald-400" />
            <span>Automated Policy Checks</span>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
            {action.policy_checks.map((check, idx) => (
              <div
                key={idx}
                className="p-2 rounded bg-neutral-900/50 border border-neutral-800 flex items-center justify-between text-[11px]"
              >
                <span className="text-neutral-300">{check.name}</span>
                <span className="font-mono text-neutral-400">{check.status}</span>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Supporting Evidence */}
      {action.supporting_evidence && action.supporting_evidence.length > 0 && (
        <div className="pt-1 flex flex-wrap items-center gap-2">
          <span className="text-[10px] text-neutral-500">Supporting Evidence:</span>
          {action.supporting_evidence.map((ev, idx) => (
            <button
              key={idx}
              type="button"
              onClick={() => openEvidence(ev)}
              className="inline-flex items-center gap-1 px-2.5 py-1 rounded bg-neutral-900 hover:bg-neutral-800 border border-neutral-800 text-sky-400 hover:text-sky-300 font-mono text-[11px] transition-colors"
            >
              <Link2 className="w-3 h-3" />
              <span>{ev.filename || ev.source_id} (p.{ev.page_number})</span>
            </button>
          ))}
        </div>
      )}

      {/* Rejection Input (if activated) */}
      {showRejectInput && (
        <div className="p-3 bg-rose-950/20 border border-rose-900/40 rounded-lg space-y-2">
          <label className="text-[11px] text-rose-300 font-medium">Rejection Reason</label>
          <input
            type="text"
            value={rejectionReason}
            onChange={(e) => setRejectionReason(e.target.value)}
            placeholder="Provide neutral justification..."
            className="w-full bg-neutral-950 border border-rose-800/60 rounded px-3 py-1.5 text-rose-200 text-xs"
          />
          <div className="flex gap-2 justify-end">
            <button
              type="button"
              onClick={() => setShowRejectInput(false)}
              className="px-3 py-1 rounded hover:bg-neutral-800 text-neutral-400"
            >
              Cancel
            </button>
            <button
              type="button"
              onClick={handleReject}
              disabled={isUpdating || !rejectionReason.trim()}
              className="px-3 py-1 rounded bg-rose-600 hover:bg-rose-500 text-white font-medium disabled:opacity-50"
            >
              Confirm Rejection
            </button>
          </div>
        </div>
      )}

      {/* Controls Bar */}
      <div className="pt-3 border-t border-neutral-800 flex flex-wrap items-center justify-between gap-3">
        <div className="flex items-center gap-2">
          {isEditing ? (
            <button
              type="button"
              onClick={handleSaveEdit}
              disabled={isUpdating}
              className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded bg-emerald-600 hover:bg-emerald-500 text-white font-medium"
            >
              <Save className="w-3.5 h-3.5" />
              <span>Save Edits</span>
            </button>
          ) : (
            isDraftOrPending && (
              <button
                type="button"
                onClick={() => setIsEditing(true)}
                className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded bg-neutral-900 hover:bg-neutral-800 border border-neutral-700 text-neutral-200"
              >
                <Edit3 className="w-3.5 h-3.5" />
                <span>Edit Payload</span>
              </button>
            )
          )}
        </div>

        {/* Approval Actions gated by permissions & status */}
        <div className="flex items-center gap-2">
          {canApprove && isDraftOrPending && (
            <>
              <button
                type="button"
                onClick={() => setShowRejectInput(true)}
                disabled={isUpdating || showRejectInput}
                className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded border border-rose-800/60 text-rose-300 hover:bg-rose-950/40"
              >
                <XCircle className="w-3.5 h-3.5" />
                <span>Reject</span>
              </button>
              <button
                type="button"
                onClick={handleApprove}
                disabled={isUpdating}
                className="inline-flex items-center gap-1.5 px-4 py-1.5 rounded bg-emerald-600 hover:bg-emerald-500 text-white font-medium"
              >
                <CheckCircle className="w-3.5 h-3.5" />
                <span>Approve Action</span>
              </button>
            </>
          )}

          {canApprove && isApproved && (
            <button
              type="button"
              onClick={handleExecute}
              disabled={isUpdating}
              className="inline-flex items-center gap-1.5 px-4 py-1.5 rounded bg-sky-600 hover:bg-sky-500 text-white font-medium"
            >
              <Send className="w-3.5 h-3.5" />
              <span>Execute Action</span>
            </button>
          )}
        </div>
      </div>
    </div>
  );
};
